export { PostI, CategoryI, CommentI } from './components/'
export { StoreStateI } from './reducers'
export { CategoriesStateI } from './reducers/Categories'
export { PostStateI } from './reducers/Posts'
export { APIPostSendNewI, APIPostSendEditI, APIPostI, APICategoriesI } from './utils/ReadableAPI'
